# Generated by Django 5.0.1 on 2025-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_strength', models.IntegerField(default=0)),
                ('match_score', models.FloatField(default=0.0)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mutual_connections_count', models.IntegerField(default=0)),
                ('common_interests', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mutual_connections', models.IntegerField(default=0)),
                ('match_score', models.FloatField(default=0.0)),
                ('connection_strength', models.FloatField(default=0.0)),
                ('common_interests', models.JSONField(blank=True, default=list)),
                ('match_highlights', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_highlights', models.JSONField(blank=True, default=list)),
                ('common_interests', models.JSONField(blank=True, default=list)),
                ('mutual_connections', models.IntegerField(default=0)),
                ('strong_connections', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
