# Generated by Django 5.0.1 on 2025-06-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMember',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='LinkPreview',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageEffect',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
        migrations.DeleteModel(
            name='MessageThread',
        ),
    ]
