# Generated by Django 5.0.1 on 2025-05-27 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_participant1_conversation_participant2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'direct')), fields=('participant1', 'participant2', 'type'), name='unique_direct_conversation'),
        ),
    ]
