# Generated by Django 5.0.1 on 2025-05-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_file_alter_message_content_message_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/thumbnails/'),
        ),
    ]
