# Generated by Django 5.0.1 on 2025-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_file_duration_file_file_type_file_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/groudefault.jpeg', null=True, upload_to='group_avatars/'),
        ),
    ]
