# Generated by Django 5.0.1 on 2025-06-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_default_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
