# Generated by Django 5.0.1 on 2025-06-09 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('voice', 'Voice'), ('video', 'Video'), ('mixed', 'Mixed Content')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='chat_messag_message_973666_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.JSONField(default=list),
        ),
    ]
