# Generated by Django 5.0.1 on 2025-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
