# Generated by Django 5.0.1 on 2025-06-09 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat_attachments/thumbnails/')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chat.file'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type'], name='chat_file_file_ty_72678a_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['category'], name='chat_file_categor_ddda31_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created_at'], name='chat_file_created_982afe_idx'),
        ),
    ]
