# Generated by Django 5.0.1 on 2025-06-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_messagethread_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='parent_message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='chat.message'),
        ),
    ]
