# Generated by Django 5.0.1 on 2025-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_messagethread_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_thread_reply',
            field=models.BooleanField(default=False),
        ),
    ]
