# Generated by Django 5.0.1 on 2025-06-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_message_is_thread_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('quick_reply', 'Quick Reply'), ('context_based', 'Context Based'), ('smart_completion', 'Smart Completion'), ('topic_suggestion', 'Topic Suggestion'), ('emotion_based', 'Emotion Based')], max_length=20)),
                ('content', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.JSONField(default=dict)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_suggestions', to='chat.conversation')),
                ('used_in_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_used', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'user', 'status'], name='chat_messag_convers_b624e0_idx'), models.Index(fields=['suggestion_type', 'confidence_score'], name='chat_messag_suggest_a48bf6_idx'), models.Index(fields=['created_at', 'expires_at'], name='chat_messag_created_a58f73_idx')],
            },
        ),
    ]
