# Generated by Django 5.0.1 on 2025-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_messagesuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesuggestion',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='messagesuggestion',
            name='used_in_message',
        ),
        migrations.RemoveField(
            model_name='messagesuggestion',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='linkpreview',
            name='chat_linkpr_message_9a8028_idx',
        ),
        migrations.AddIndex(
            model_name='linkpreview',
            index=models.Index(fields=['message'], name='chat_linkpr_message_e2a5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='linkpreview',
            index=models.Index(fields=['url'], name='chat_linkpr_url_2173b5_idx'),
        ),
        migrations.DeleteModel(
            name='MessageSuggestion',
        ),
    ]
