# Generated by Django 5.0.1 on 2025-06-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_remove_messagesuggestion_conversation_and_more'),
        ('stories', '0002_remove_story_allow_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='stories.story'),
        ),
    ]
