# Generated by Django 5.0.1 on 2025-06-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='story',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='storyanalytics',
            name='comments_count',
        ),
        migrations.DeleteModel(
            name='StoryComment',
        ),
    ]
