# Generated by Django 5.0.1 on 2025-05-30 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentrating',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='community.comment'),
        ),
        migrations.AddField(
            model_name='commentrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.community'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='community.community'),
        ),
        migrations.AddField(
            model_name='comment',
            name='community_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='event',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='community.community'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalpost',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='community.community'),
        ),
        migrations.AddField(
            model_name='comment',
            name='personal_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.personalpost'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='community_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='personal_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.personalpost'),
        ),
        migrations.AddField(
            model_name='postrating',
            name='community_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='postrating',
            name='personal_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='community.personalpost'),
        ),
        migrations.AddField(
            model_name='postrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='community.reply'),
        ),
        migrations.AddField(
            model_name='replyrating',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='community.reply'),
        ),
        migrations.AddField(
            model_name='replyrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='community_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='personal_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='community.personalpost'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_objects', to='community.community'),
        ),
        migrations.AddField(
            model_name='personalpost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_posts', to='community.topic'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_posts', to='community.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='commentrating',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['user', 'last_active'], name='community_c_user_id_b50a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['community', 'role'], name='community_c_communi_94ed24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('user', 'community')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['community', 'start_date'], name='community_e_communi_3d9144_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'is_active'], name='community_e_status_e54164_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='postrating',
            unique_together={('community_post', 'user'), ('personal_post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='replyrating',
            unique_together={('reply', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('user', 'community_post'), ('user', 'personal_post')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'community')},
        ),
        migrations.AddIndex(
            model_name='personalpost',
            index=models.Index(fields=['author', 'visibility', 'created_at'], name='community_p_author__e8092d_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['community', 'visibility', 'created_at'], name='community_c_communi_4dd8b5_idx'),
        ),
    ]
