# Generated by Django 5.0.1 on 2025-06-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, default='community_banners/default_community_banner.png', help_text='Community cover photo (recommended size: 1200x400px)', null=True, upload_to='community_banners/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, default='community_icons/default_community_icon.png', help_text='Community profile image/icon (recommended size: 256x256px)', null=True, upload_to='community_icons/'),
        ),
    ]
