# Generated by Django 5.0.14 on 2025-05-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='assistant_c_user_id_634679_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='assistant_c_created_dbf443_idx',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
