# Generated by Django 5.0.1 on 2025-06-17 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_airatinginsight_assistantinterest_assistantmemory_and_more'),
        ('community', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation_id'], name='assistant_c_convers_10e0f2_idx'),
        ),
    ]
