# Generated by Django 5.0.1 on 2025-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_chatmessage_conversation_id_chatmessage_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
