# Generated by Django 5.0.1 on 2025-06-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_assistantmemory_message_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmemory',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True, help_text='Last time the user interacted with the assistant'),
        ),
    ]
