# Generated by Django 5.0.1 on 2025-05-30 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_connection_requests', models.BooleanField(default=True)),
                ('email_community_invites', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_achievements', models.BooleanField(default=True)),
                ('email_events', models.BooleanField(default=True)),
                ('push_connection_requests', models.BooleanField(default=True)),
                ('push_community_invites', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_achievements', models.BooleanField(default=True)),
                ('push_events', models.BooleanField(default=True)),
                ('in_app_connection_requests', models.BooleanField(default=True)),
                ('in_app_community_invites', models.BooleanField(default=True)),
                ('in_app_messages', models.BooleanField(default=True)),
                ('in_app_achievements', models.BooleanField(default=True)),
                ('in_app_events', models.BooleanField(default=True)),
                ('email_community_join', models.BooleanField(default=True)),
                ('email_community_join_accepted', models.BooleanField(default=True)),
                ('email_community_join_rejected', models.BooleanField(default=True)),
                ('email_community_role_change', models.BooleanField(default=True)),
                ('push_community_join', models.BooleanField(default=True)),
                ('push_community_join_accepted', models.BooleanField(default=True)),
                ('push_community_join_rejected', models.BooleanField(default=True)),
                ('push_community_role_change', models.BooleanField(default=True)),
                ('in_app_community_join', models.BooleanField(default=True)),
                ('in_app_community_join_accepted', models.BooleanField(default=True)),
                ('in_app_community_join_rejected', models.BooleanField(default=True)),
                ('in_app_community_role_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('community_invite', 'Community Invitation'), ('community_join', 'Community Join Request'), ('community_join_accepted', 'Community Join Accepted'), ('community_join_rejected', 'Community Join Rejected'), ('community_role_change', 'Community Role Change'), ('message', 'New Message'), ('achievement', 'Achievement Unlocked'), ('event', 'Event Update'), ('mention', 'Mention'), ('like', 'Like'), ('comment', 'Comment')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
